version: '3.8'

services:
  selenium:
    container_name: 'selenium_service'
    image: seleniarm/standalone-chromium:4.1.2-20220227
    privileged: true
    hostname: chrome
    restart: unless-stopped
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - START_XVFB=false
    ports:
      - "4444:4444"
    networks:
      - selenium_nw
  redis:
    image: "redis:alpine"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis
    networks:
      - data_sharing
  app:
    container_name: 'fast_api_service'
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - selenium
      - redis
    restart: unless-stopped
    networks:
      - backend_nw
      - data_sharing
    volumes:
      - ./app/:/app
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
    command: 'python main.py'

  scrape:
    container_name: 'scrape_service'
    build:
      context: ./selenium
      dockerfile: Dockerfile.dev
    depends_on:
      - selenium
      - redis
    restart: unless-stopped
    networks:
      - selenium_nw
      - data_sharing
    volumes:
      - ./selenium/:/selenium
    ports:
      - 5050:5050
    environment:
      - PYTHONUNBUFFERED=1
      - REMOTE_SELENIUM_URL=${REMOTE_SELENIUM_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
    command: 'python main.py'

networks:
  backend_nw:
    name: services_network
    driver: bridge

  data_sharing:
    driver: bridge

  selenium_nw:
    name: selenium_network
    driver: bridge
