version: '3.8'

services:
  selenium:
    container_name: 'selenium_service'
    image: selenium/standalone-chrome
    privileged: true
    hostname: chrome
    restart: unless-stopped
    environment:
      - DISPLAY=:99
    ports:
      - "4444:4444"
    networks:
      - selenium_nw
  app:
    container_name: 'fast_api_service'
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      - backend_nw
    volumes:
      - ./app/:/app
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
    command: 'python main.py'

  scrape:
    container_name: 'scrape_service'
    build:
      context: ./selenium
      dockerfile: Dockerfile.dev
    depends_on:
      - selenium
    restart: unless-stopped
    networks:
      - selenium_nw
      - spark_nw
    volumes:
      - ./selenium/:/selenium
    ports:
      - 5050:5050
    environment:
      - PYTHONUNBUFFERED=1
      - REMOTE_SELENIUM_URL=${REMOTE_SELENIUM_URL}
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - BINANCE_NAME=${BINANCE_NAME}
      - BINANCE_GENERAL_URL=${BINANCE_GENERAL_URL}
    command: 'python main.py'
  

networks:
  backend_nw:
    name: services_network
    driver: bridge
  
  selenium_nw:
    name: selenium_network
    driver: bridge

