version: '3.8'

services:
  selenium:
    container_name: 'selenium_service'
    image: seleniarm/standalone-chromium:4.1.2-20220227
    privileged: true
    hostname: chrome
    restart: unless-stopped
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - START_XVFB=false
    ports:
      - "4444:4444"
    networks:
      - selenium_nw
  app:
    container_name: 'fast_api_service'
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - selenium
    restart: unless-stopped
    networks:
      - backend_nw
    volumes:
      - ./app/:/app
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
    command: 'uvicorn src.app:app --reload --host 0.0.0.0 --port 5000'

  scrape:
    container_name: 'scrape_service'
    build:
      context: ./selenium
      dockerfile: Dockerfile.dev
    depends_on:
      - selenium
    restart: unless-stopped
    networks:
      - selenium_nw
    volumes:
      - ./selenium/:/selenium
    ports:
      - 5050:5050
    environment:
      - PYTHONUNBUFFERED=1
      - REMOTE_SELENIUM_URL=${REMOTE_SELENIUM_URL}
    command: 'python main.py'

networks:
  backend_nw:
    name: services_network
    driver: bridge

  selenium_nw:
    name: selenium_network
    driver: bridge
